version: '1.0.0'
services:
  next-front:
    container_name: front_next
    restart:
      always
    image:
      front
    build: ./frontend
    environment:
      TZ: Asia/Seoul
    ports:
      - "3000:3000"
    networks:
      - import_network
      - import_home_network
    depends_on:
      - node-server

  node-server:
    container_name: back_node
    restart:
      always
    image:
      back
    build: ./backend
    environment:
      TZ: Asia/Seoul
    ports:
      - "4000:4000"
    volumes:
      #이미지 파일 저장 경로
      - ./backend/image:/app/image
    networks:
      - import_network
      - import_home_network
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    build: ./mariadb
    restart: always
    # 환경에 따라 변경
    ports:
      - "3306"
    volumes:
      - ./mariadb/db/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
      # DB 데이터 저장 디렉터리
      - ./mariadb/data:/var/lib/mysql
      # 설정 파일 저장될 위치
      - ./mariadb/config:/etc/mysql/conf.d
    env_file:
      - "./.env"
    networks:
      - import_network

networks:
  import_network:
    driver: bridge
  import_home_network:
    driver: bridge
    external: true