version: '1.0.0'
services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./nginx
    restart: always
    #외부와 소통하는 경우에는 ports로 포트 설정.
    ports:
      - "80:80/tcp"
      - "443:443"
    volumes:
    #docker-compose.yml과 같은 레벨에 둔 nginx.conf를 mount.
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - import_network
    environment:
      - TZ=Asia/Seoul

  next-front:
    container_name: front_next
    restart:
      always
    image:
      front
    build: ./frontend
    environment:
      TZ: Asia/Seoul
    ports:
      - "3000:3000"
    networks:
      - import_network
    depends_on:
      - node-server

  node-server:
    container_name: back_node
    restart:
      always
    image:
      back
    build: ./backend
    environment:
      TZ: Asia/Seoul
    ports:
      - "4000:4000"
    networks:
      - import_network
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    build: ./mariadb
    restart: always
    # 환경에 따라 변경
    ports:
      - "3306"
    volumes:
      - ./mariadb/db/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
      # DB 데이터 저장 디렉터리
      - ./mariadb/data:/var/lib/mysql
      # 설정 파일 저장될 위치
      - ./mariadb/config:/etc/mysql/conf.d
    env_file:
      - "./.env"
    networks:
      - import_network

networks:
  import_network:
    driver: bridge