import { NextResponse } from "next/server";

export async function GET(req: Request, res: Response) {
  return NextResponse.json([
    {
      userId: 1,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 2,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 3,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 2,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 4,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 5,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 4,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 6,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 7,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 5,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 8,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 9,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 10,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 11,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 12,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 13,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 14,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 15,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 16,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 17,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 18,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 19,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 20,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 21,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 22,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 23,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 24,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 25,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 26,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 27,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 28,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 29,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 30,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
    {
      userId: 31,
      nick_name: "강다짐",
      createdAt: "2023-03-11 08:00:00",
      email: "pkss0626@naver.com",
      rank: 3,
      profileImg: null,
      department: "모바일융합공학과",
      grade: "2",
      blog: "mayrang.velog.io",
      github_url: "mayrang.github.com",
      framework: "nextjs",
      language: "typescript",
    },
    {
      userId: 32,
      nick_name: "정다짐",
      createdAt: "2023-03-12 08:00:00",
      email: "pgss0626@gmail.com",
      rank: 1,
      profileImg: null,
    },
  ]);
}
